<p>
Sr.(a)&nbsp;{NOMBRES}<br><br>
{N_CUERPO_NOTIFICACION_LISTA_VERSION_1} {CODIGONOMBRE} {N_CUERPO_NOTIFICACION_LISTA_VERSION_2} {VERSION}, {N_CUERPO_NOTIFICACION_LISTA_VERSION_3}:<br>
{LISTADOCARGOS}
</p>
<br>
