<?php
//{CUADRO\s[A-Z]|^[A-Z][A-Z]*(| [IVXLCM]+)|[1-2] SEMESTRE DE 2\.0[0-9]{2}} 
//$Exp['Nombre_archivo'][0]//Expresion 1
//$Exp['Nombre_archivo'][1]//Expresion 2
/*01*/$Exp['EBO00A0A.051'][0] = '((([0-9]{1,3}\.[0-9]{3}(|\.[0-9]{3})\s*(-|Y)\s*|HASTA\s*)([0-9]{1,3}\.[0-9]{3}(\.[0-9]{3}|)|MAS)|NO REMUNERADO|NO DECLARADOS|TOTAL|VARONES|HEMBRAS)(\s*([0-9]{1,7}|--)){6})';
/*01*/$Exp['EBO00A0A.051'][1] = '{(([0-9]{1,3}\.[0-9]{3}(|\.[0-9]{3})\s*(-|Y)\s*|HASTA\s*)([0-9]{1,3}\.[0-9]{3}(\.[0-9]{3}|)|MAS)|NO REMUNERADO|NO DECLARADOS|TOTAL|VARONES|HEMBRAS)|([0-9]{1,7}|--)}';
/*02*/$Exp['EBO00B0A.051'][0] = '{([0-9]{2}\s*(-|Y)\s*([0-9]{2}|MAS)|TOTAL|VARONES|HEMBRAS)(\s*([0-9]{1,7}|--)){6}}';
/*02*/$Exp['EBO00B0A.051'][1] = '{([0-9]{2}\s*(-|Y)\s*([0-9]{2}|MAS)|TOTAL|VARONES|HEMBRAS)|([0-9]{1,7}|--)}';
/*03*/$Exp['EBO00C0A.051'][0] = '{(TOTAL|-(ANALFABETA|SIN NIVEL|BASICA|MEDIA DIVERSIFICADA\s*PROFESIONAL|TECNICO SUPERIOR|UNIVERSITARIO|NO DECLARADO)|HEMBRAS|VARONES)(\s*([0-9]{1,7}|--)){6}}';
/*03*/$Exp['EBO00C0A.051'][1] = '{(TOTAL|-(ANALFABETA|SIN NIVEL|BASICA|MEDIA DIVERSIFICADA\s*PROFESIONAL|TECNICO SUPERIOR|UNIVERSITARIO|NO DECLARADO)|HEMBRAS|VARONES)|([0-9]{1,7}|--)}';
/*04*/$Exp['EBO00D0A.051'][1] = '{(TOTAL|HEMBRAS|VARONES|EN ACTIVIDADES AGRICOLAS|EN ACTIVIDADES NO AGRICOLAS|-(EXPLOTACION DE HIDROCAR-\s*BUROS, MINAS Y CANTERAS|INDUSTRIAS MANUFACTURERAS|ELECTRICIDAD, GAS Y AGUA|CONSTRUCCION|COMERCIO AL POR MAYOR Y\s*AL POR MENOR Y RESTAURAN-\s*TES Y HOTELES|TRANSPORTE, ALMACENAMIEN-\s*TO Y COMUNICACIONES|ESTABLECIMIENTOS FINAN-\s*CIEROS, SEGUROS, BIENES\s*INMUEBLES Y SERVICIOS\s*PRESTADOS A LAS EMPRESAS|SERVICIOS COMUNALES, SO-\s*CIALES Y PERSONALES|ACTIVIDADES NO BIEN ESPE-\s*CIFICADAS Y NO DECLARADAS))(\s*([0-9]{1,7}|--)){6}}';
/*04*/$Exp['EBO00D0A.051'][0] = '{((TOTAL|HEMBRAS|VARONES|EN ACTIVIDADES AGRICOLAS|EN ACTIVIDADES NO AGRICOLAS|-(EXPLOTACION DE HIDROCAR-\s*BUROS, MINAS Y CANTERAS|INDUSTRIAS MANUFACTURERAS|ELECTRICIDAD, GAS Y AGUA|CONSTRUCCION|COMERCIO AL POR MAYOR Y\s*AL POR MENOR Y RESTAURAN-\s*TES Y HOTELES|TRANSPORTE, ALMACENAMIEN-\s*TO Y COMUNICACIONES|ESTABLECIMIENTOS FINAN-\s*CIEROS, SEGUROS, BIENES\s*INMUEBLES Y SERVICIOS\s*PRESTADOS A LAS EMPRESAS|SERVICIOS COMUNALES, SO-\s*CIALES Y PERSONALES|ACTIVIDADES NO BIEN ESPE-\s*CIFICADAS Y NO DECLARADAS))|([0-9]{1,7}|--))}';
/*05*/$Exp['EBO00F0A.051'][1] = '{(((TOTAL|NO)(\sDECLARADOS|))|VARONES|HEMBRAS|[0-9]{1,2}\s*(-|Y)\s*([0-9]{1,2}|MAS)\s*PERSONAS)(\s*([0-9]{1,7}|--)){10}}';
/*05*/$Exp['EBO00F0A.051'][0] = '{(((TOTAL|NO)(\sDECLARADOS|))|VARONES|HEMBRAS|[0-9]{1,2}\s*(-|Y)\s*([0-9]{1,2}|MAS)\s*PERSONAS)|(([0-9]{1,7}|--))}';
/*06*/$Exp['EBO00G0A.051'][0] = '{(TOTAL|VARONES|HEMBRAS|NO DECLARADO|(MENOS|MAS)\sDE\s[0-9]{2}|[0-9]{2}-[0-9]{2})\.*(\s*([0-9]{1,7}|--)){6}}';
/*06*/$Exp['EBO00G0A.051'][1] = '{(TOTAL|VARONES|HEMBRAS|NO DECLARADO|(MENOS|MAS)\sDE\s[0-9]{2}|[0-9]{2}-[0-9]{2})|([0-9]{1,7}|--)}';
/*07*/$Exp['EBO00H0A.051'][1] = '{((([0-9]{1,3}\.[0-9]{3}(|\.[0-9]{3})\s*(-|Y)\s*|HASTA\s*)([0-9]{1,3}\.[0-9]{3}(|\.[0-9]{3})|MAS)|NO DECLARADO|TOTAL|VARONES|HEMBRAS)(\s*([0-9]{1,7}|--)){7})}';
/*07*/$Exp['EBO00H0A.051'][0] = '{(([0-9]{1,3}\.[0-9]{3}(|\.[0-9]{3})\s*(-|Y)\s*|HASTA\s*)([0-9]{1,3}\.[0-9]{3}(\.[0-9]{3}|)|MAS)|NO DECLARADO|TOTAL|VARONES|HEMBRAS)|([0-9]{1,7}|--)}';







?>